service:
  name: nest-serverless-hello-world

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          cors: true
          path: '{proxy+}'
          method: any
      - http:
          cors: true
          path: '/'
          method: any
  ws:
    handler: src/lambda.handler
    events:
      - websocket:
          route: $disconnect
      - websocket:
          route: $connect
      - websocket:
          route: $default
      - websocket:
          route: definedroute

package:
  individually: true
