service:
  name: nest-serverless-hello-world

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  main:
    handler: src/aws-lambda-fastify.handler
    events:
      # - http:
      #     cors: true
      #     path: '{proxy+}'
      #     method: any
      - http:
          cors: true
          path: '/fastify'
          method: any

  ws:
    # To test other
    # handler: src/aws-lambda-fastify.handler
    handler: src/serverless-fastify.handler
    events:
      - websocket:
          route: $disconnect
      - websocket:
          route: $connect
      - websocket:
          route: $default
      - websocket:
          route: definedroute

  newHttpApi:
    handler: src/serverless-fastify.handler
    events:
      - httpApi:
          method: '*'
          path: /serverless/{proxy+}
          cors: true

package:
  individually: true
